# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy to Develop Server

on:
  push:
    branches: [develop]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: "mysql:5.7"
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: test
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      # Downloads a copy of the code in your repository before running CI tests
      - name: Check out repository code
        uses: actions/checkout@v2

      # Performs a clean installation of all dependencies in the `package.json` file
      # For more information, see https://docs.npmjs.com/cli/ci.html
      - name: Install dependencies
        run: npm ci
      #Performs Unit Testing
      - name: Run DB Migration
        run: npx prisma migrate dev --name ciTestMigration
        env:
          DATABASE_URL: "mysql://root:@127.0.0.1:3306/test?schema=public"
      - name: Run Build
        run: npm run build

  # deploy:
  #   needs: [test]
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: SSH to DO Droplets
  #       uses: appleboy/ssh-action@master
  #       with:
  #         host: ${{ secrets.HOST }}
  #         username: ${{ secrets.USERNAME }}
  #         password: ${{ secrets.PASSWORD }}
  #         port: ${{ secrets.PORT }}
  #         script: |
  #           cd /root/projectname
  #           sudo git add . && git stash
  #           sudo git fetch origin develop
  #           sudo git reset --hard origin/develop 
  #           npx prisma migrate dev --name devMigration
  #           npm run seed
  #           npm install
  #           pm2 restart projectname
